### ISSUE TITLE
Migrate account balances tests to cypress

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1062]
## Problem Definition

Split part of #638.

Before the re-write to vue.js we had tests for adding accounts these tests have not been migrated to Cypress yet.

We should migrate these tests to Cypress and delete any leftover unmaintained spectron tests.

The spectron tests have been removed but they can be found [here](https://github.com/rotki/rotki/blob/18e954912e88d45f13a39af67d41bd1b798a9b68/frontend/app/tests/spectron/specs/accounts-balances.spec.ts)

The accounts are available here: https://github.com/rotki/rotki/blob/develop/frontend/app/cypress.env.json
And can be accessed by `Cypress.env('...')` 

### Tasks

- [ ] Add an ETH account 
- [ ] Verify that the account is added
- [ ] Add a BTC account
- [ ] Verify that the account is added

#### Optional
- [ ] The eth account might have some history, so it might make senset to verify also that an `ETH` entry is displayed on the dashboard.
