### ISSUE TITLE
Display token allowance per token per address

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1215]
## Abstract

As stated by jmiehau in this [tweet](https://twitter.com/jmiehau/status/1287087218742439936) since Rotki aggregates data over all the addresses of a user it would be really beneficial for users to be able to check what addresses they have allowed to spend their tokens for each token they own.

Also we should warn users if they have given approvals to a malicious address.

## Task

- [ ] Create an allowance query API endpoint per address per token and if no token or address is given query all.
- [ ] Find out a good way to show that to the user in the UI
- []  Create periodic task to go through approval (and revoke) events, to see if any of the user's tracked addresses have an active approval to an exploitable contract.
- [ ] If they do, warn them much like we do with the new tokens detection. Users should be able to ignore such a warning and it should not spam them as @yabirgb mentioned here: https://discord.com/channels/657906918408585217/683245846070165504/1311294706583470090

**Comment by LefterisJP** [comment]
Let's do this. I can imagine this being an easy to do and useful feature.

1. This should be in the blockchain & balances section under each account, where we show each account's tokens. 
2. For each token we should be able to click on it or somewhere there in order to show a list of addresses that are allowed to spend it for our address and an amount of how much of the token each address is allowed to spend.
3. Would also be nice to have a link to https://revoke.cash/ by @rkalis there since rotki does not yet allow control of user's keys, so if they wanted to revoke any approvals they would need it.

**Comment by LefterisJP** [comment]
Instead of querying other APIs we can also do that (like so many other things) by processing all events we got.

**Comment by rishabhRsinghvi** [comment]
can you please assign this to me?
