### ISSUE TITLE
Add each asset's current price in the balances tables

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1228]
## Abstract

A Telegram user requested this. They mentioned that having the current price of each asset in the balance table of all assets in the dashboard could be beneficial. This could be extrapolated to all balance tables.

## Task

- [ ] Consider if this would make sense as a feature
- [ ] Implement it by tweaking the backend API calls and the docs. Data is already there so should be easy to send.
- [ ] Add the column in the frontend

**Comment by A2be** [comment]
COMMENT: I'm a new user of Rotki, and haven't even populated the app yet.

However, I think that IF you decide to implement this feature enhancement request, you should do a little thinking about what level of granularity, and what level of time currency, this might be useful to a broad set of your users.

For example: is daily granularity (say, end of day UTC time?) an improvement for many users?
Is "as of the last hour, at the hour, needed?"
Is the person looking for near-real-time info to be in Rotki, like "up to the minute", as if you are continously running a background process mapping current oracle-provided digital asset prices onto whatever assets the rotki user cares about???

I don't know; but do think that the granularity must be considered as a specific detail of the requirement statement.

**Comment by LefterisJP** [comment]
Hey @A2be thanks a lot for taking the time to comment on the issue with your perspective.

I imagined that we would be querying the price at exactly the same time as the balances are queried.

Reasoning: 

All balances currently have the `amount` of the asset, and its `USD/EUR/XXX` equivalent. The latter is calculated by taking the current price into account. We just don't show the price in the table. The user in telegram wanted to be able to see it.

It's trivial to just do a division `usd_value / price` to get the price on the one hand, but it also makes sense that the user wants to see it in the table.

**Comment by adrien-be** [comment]
+1

Good remark on the granularity. My guess is that regardless of the solution you take, it would be nice to know when the prices were last pulled and consider adding a warning if the price is considered old. Crypto is highly volatile so it "old" can sometimes mean minutes.
