### ISSUE TITLE
Allow customization of numerical displays

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1235]
## Abstract

People from different countries expect numbers to be displayed in different ways. Different thousands separator symbol, different decimal point symbol, different location for the currency symbol.

Examples:

:de:  -> 500.000,55€
:us:  -> €500,000.55

We should offer customization of number displays in the frontend.
## Task

- [ ] Add setting to allow customization of decimal point symbol
- [ ] Add setting to allow customization of thousands separator symbol
- [ ] Add setting to allow customization of currency symbol location
- [ ] Allow customization of the above settings from the frontend
- [ ] Display all numbers according to the settings

**Comment by isidorosp** [comment]
Fully agreed that we need something like this but I do not think it is a simple issue to implement (or rather, this specific proposal is, but doing it "right" isn't).

1) Eventually this should be part of a locale setting and then user override-able if desired, and that's non-trivial to implement. There are things to deal with like currency symbol placement,  that currencies do not actually have the same currency precision. Some currencies have 0 decimals, such as the Japanese Yen, others have 3 (like most variants of the Dinar), whereas most have 2. Some currencies have 2 but there are local laws which say all numbers in payments and accounting must be integers (Hungarian Forint). Right now we are rounding all fiat currency representation to 2 which isn't strictly correct.
Some additional info on this here: https://en.wikipedia.org/wiki/ISO_4217#Code_formation
and downloadable for us here: https://datahub.io/JohnSnowLabs/iso-4217-currency-codes#data-cli
In general there are libraries to deal with these things (numerals.js / numbro.js) but we'd need to investigate how nicely they can play with BigNumber.js. I did a little digging and also found this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat which is relatively new and is a JS library that is built into newer versions of JS that supports internationalization of time+date+numbers.

2) Right now since we only display numbers in a certain way (most importantly the decimal symbol), it's somewhat clear how we expect numbers to be input as well. However if we display things in a user-defined format, we should also expect that users may input numbers in that same format (or they may not): e.g. what happens if a user enters a manual balance/trade and for amount they put "22.500" instead of "22,500" or "22500"?

**Comment by LefterisJP** [comment]
@isidorosp Setting this according to a locale is another step. We don't need to go for the perfect solution to the issue from the get go.

Offering the customization I mentioned above should be a good way to start.

> Right now since we only display numbers in a certain way (most importantly the decimal symbol), 

That's true, but as I said, step by step. can't offer everything at one go.
