### ISSUE TITLE
Deprecate Fiat Balances and remove unneeded DB data in the next DB upgrade

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1265]
## Abstract

After https://github.com/rotki/rotki/issues/1251 there will be some data that is going to remain in the rotki DB which are not needed and should be deleted. But no need to create a DB upgrade only for them. So they should be included in the next DB upgrade.

## Task

In the next DB upgrade:

- [ ] Remove all owned eth tokens as this setting is no longer going to be used
`DELETE FROM multisettings WHERE name="eth_token";`
- [ ] If the user had any alethio credentials remove them.
`DELETE FROM external_service_credentials WHERE name="alethio";`
- [ ] Delete the possibility of alethio keys from the `ExternalService` [enum](https://github.com/rotki/rotki/blob/db01f5c1ffaeeb3fdddd627051dcc715a0f720c7/rotkehlchen/typing.py#L64). Since it was the last value it can be replaced in the future.

**Comment by A2be** [comment]
FWIW, @LefterisJP , I'm having a bit of a discussion with someone from Alethio (now CoDeFi Data) over on the ConsenSys Discord.  Telling me that: 
` I don't believe any API Endpoints have changed at this point. If you have specific reports you'd like me to look into please share. The Alethio API for mainnet, now the Codefi Data Fundamental API (https://medium.com/alethio/the-future-of-alethio-c4fd511e4c03), will continue to see support.`

So, don't know if that helps.  But I know one user and you were talking about something in the Alethio querries in v1.6.1 not working for something.

**Comment by LefterisJP** [comment]
Thank you for the feedback @A2be, but Alethio is shutting down and has had many problems lately (https://github.com/rotki/rotki/issues/1251), so we have removed it and the change will be effective in the next version.

**Comment by A2be** [comment]
No worries.  Just thought I'd let you know.
