### ISSUE TITLE
Allow Rotki to pass connections via a proxy

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1348]
## Abstract

A telegram user requested this feature. Motivation is:

> A lot of stuff is IP blocked in China, including etherscan, so this makes the app unusable without extra measures.

## Task

- [ ] Add a new setting for proxy congiruation
- [ ] Expose it in the UI
- [ ] Use the configured proxies in all backend requests. Check python requests docs: https://requests.readthedocs.io/en/master/user/advanced/#proxies
