### ISSUE TITLE
Properly calculate historical prices for yearn vault tokens

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1470]
## Problem Definition

As seen in #1469, at the moment we don't really calculate the proper historical price for yearn vault tokens as we can't. Price for those tokens is not pulled in from any external oracles but is instead pulled from the chain itself. By doing`eth_call` on various contracts and then some calculations (along with price queries of the underlying token). Examples here: https://github.com/rotki/rotki/blob/23988d5b28532eaa079080c4572b48c63b90a642/rotkehlchen/chain/ethereum/defi.py#L32

The problem is that for more than 128 blocks you need an archive node and we don't have one setup from where we could pull the data yet.

## Task

- [ ] Set an archive node up for the premium users.
- [ ] Create a new premium API call to query the archive node
- [ ] Adjust all calls in etherum/defi.py and ethereum/yearn/vaults.py to utilize the archive node calls.
- [ ] Remove any potential warnings in the UI for probably mistaken usd_value in events.

**Comment by LefterisJP** [comment]
With infura and alchemy offering limited archive node access for free we should implement at least a simple version of this soon
