### ISSUE TITLE
Take Binance Lending/Savings into account for profit calculation

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1505]
## Abstract

After https://github.com/rotki/rotki/pull/1503 we can now show the lending/savings balances in binance.

But users probably want a bit more detailed breakdown.

When they click on the binance balances component it should differentiate between which assets are just sitting in the account and which are in savings/lending.

We can achieve that by using this [endpoint](https://binance-docs.github.io/apidocs/spot/en/#savings-endpoints).

Also take the interest history into account in the tax profit/loss report.

## Task

- [ ] Add a new API endpoint for binance savings details (or somehow include it in the current balances one? -- need thinking -- probably new endpoint)
- [ ] In the UI, when the user clicks on the binance balances components balances should be split into what's in the normal exchange and what's in savings. For those in savings we should show how much they are earning in interest. And also how much they have earned from savings. Using [this](https://binance-docs.github.io/apidocs/spot/en/#get-interest-history-user_data-2) endpoint.
- [ ] Take the binance savings historical earnings into account in the tax profit/loss report.

**Comment by Tomson124** [comment]
+1
