### ISSUE TITLE
Allow customization in the handling of forked assets during accounting

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1610]
## Abstract

At the moment Rotki handles forked assets in a hard-coded way. Each time you buy/acquire an asset before the fork you also have a virtual buy for the forked asset at the same price.

This methodology may not work well in some jurisdictions. So we should offer customization for the handling of forked assets.

## Task

- [ ] Add a new setting for handling of forked assets. Possible values should be:
    - *Each prefork buy, buys forked asset* (current as of v1.8.1): Each time the preforked asset is purchased before the fork occurs then the same amount of forked asset is acquired at the same price.
    - *All at fork time. Source asset*: At the time of the fork the exact amount of preforked asset you had is priced and then you acquire the forked asset at the price of the time of the fork. The price here being the price of the source asset (ETH in ETH->ETC) at the time of the fork.
    - *All at fork time. Forked asset*: At the time of the fork the exact amount of preforked asset you had is priced and then you acquire the forked asset at the price of the time of the fork. The price here being the price of the forked asset (ETC in ETH->ETC) at the time of the fork.
    
- [ ] Implement the different methodologies of handling forked assets as per the setting in the backend
- [ ] Allow customization of the setting through the UI in the accounting settings component. In the UI also show an explanation of how each setting works.

**Comment by emansipater** [comment]
I like this idea.

**Comment by a7e8** [comment]
The UK has a fork treatment that is not mentioned above: https://blog.coinjar.com/crypto-tax-uk-in-2021-everything-you-need-to-know/#Hard-forks

However `All at fork time. Forked asset` is probably also fine: "Costs must be split on a just and reasonable basis" https://www.gov.uk/government/publications/tax-on-cryptoassets/cryptoassets-for-individuals

I'm not sure if you have to reduce the cost basis of the original asset. That doesn't make sense to me.

**Comment by a7e8** [comment]
Based on guidance here:

"Original coin maintains 100% cost basis, new coin(s) take zero basis"
https://www.cointracker.io/blog/cryptocurrency-taxation-in-the-united-kingdom

That should be an option as it's the simplest and not pro-rated.

**Comment by LefterisJP** [comment]
So @yabirgb you are assigned here but not sure if you are working or have worked on this. I am moving it over.

**Comment by yabirgb** [comment]
@LefterisJP Yes I was working on this but we needed to refactor the accounting part and agreed on let it for later. I'll take it as priority for 1.25

**Comment by LefterisJP** [comment]
> @LefterisJP Yes I was working on this but we needed to refactor the accounting part and agreed on let it for later. I'll take it as priority for 1.25

narrator: He didn't 

This needs to be done people. Moving it again ...
