### ISSUE TITLE
An xpub with "invalid derivation" path can't be deleted

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1641]
## Problem Definition

A user's xpub ended up in the DB and parts of the app complain for it as an invalid.

This is what the timed derivation tasks errors with in the logs:

```
[27/10/2020 09:37:02 PDT] ERROR rotkehlchen.greenlets: Task for Derive new xpub addresses died with exception: Got bad xpub path. Got: 49'/0'/0'.
Exception Name: <class 'rotkehlchen.errors.XPUBError'>
Exception Info: Got bad xpub path. Got: 49'/0'/0'
Traceback:
   File "src/gevent/greenlet.py", line 818, in gevent._greenlet.Greenlet.run
  File "rotkehlchen/chain/bitcoin/xpub.py", line 257, in check_for_new_xpub_addresses
  File "rotkehlchen/chain/bitcoin/xpub.py", line 167, in _derive_xpub_addresses
  File "rotkehlchen/chain/bitcoin/xpub.py", line 126, in derive_addresses_from_xpub_data
  File "rotkehlchen/chain/bitcoin/hdkey.py", line 274, in derive_path
  File "rotkehlchen/chain/bitcoin/hdkey.py", line 249, in _parse_derivation

[27/10/2020 09:37:02 PDT] ERROR rotkehlchen.user_messages: Task for Derive new xpub addresses died with exception: Got bad xpub path. Got: 49'/0'/0'. Check the logs for more details
```

Trying to delete the xpub also fails

```
Only got this in the logs when i manually try to delete the bad xpub.
[27/10/2020 09:47:12 PDT] INFO rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "DELETE /api/1/blockchains/BTC/xpub HTTP/1.1" 200 229 0.001417
[27/10/2020 09:47:14 PDT] DEBUG rotkehlchen.api.rest: Request successful response={"result": {"status": "completed", "outcome": {"result": null, "message": "Tried to remove non existing xpub xpub... with derivation path "}}, "message": ""}, status_code=200
```

## Task

- [x] Make the error messages better:
    - [ ] The derivation path should be part of the deletion (if there is none specify it)
    ~~- [ ] Also at the bad xpub path mention for which xpub it is~~ -> not possible at that location. But we should also not really hit that again.
- [x] Figure out how an xpub derivation path that we can't read can make it in the DB and stop it
~~- [ ] Allow deletion of xpub entries even if the xpub derivation path is "invalid"~~ Opted instead for a DB upgrade to make sure our data contains only valid entries

-----

This is for you @coblee 

Can you let me know if you do see the xpub with the "invalid derivation path" in the UI? What I understood is you see it, try to delete it and then you can't and get the error.
