### ISSUE TITLE
Allow customization of profit calculation methodology in DeFi events (either token or $ value)

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1729]
## Abstract

At the moment in most (but not all) DeFi events profit is calculated on the token in question. The two different aproaches are shown here

|Time  | Asset  | action   | amount| $ price | $ value |
| -------|:---------:| ------------:|--------:|----------:|-----------|
| 1     |  ETH     | deposit    | 10     |   1        |  10
| 2     |  ETH     |  deposit   | 5       |   1.1     |  5.5
| 3     |  ETH     |  withdraw | 2       |   2        |  4
| 4     |   ETH    |    query    | 13.2  |   2.5     |    33

For the above scenario, and with the token being ETH we end up with:

- **token value approach:**  0.2 ETH / $0.5  (value of 0.2 ETΗ at time 4)
- **$ value approach:**  0.2 ETH / $21.5 (value = 33 + 4 - 15.5 = 21.5 )

## Task

Create a new accounting option to allow customization of this. If set to token value the profit will be calculated on the token, and at the very end of the calculation the token's usd price be taken into account. While if we calculate on the usd value every step of the profit calculation needs to take into account the $ value.

Implement the above options for:

- [ ] Aave lending/borrowing
- [ ] Compound lending/borrowing
- [ ] Yearn vaults (probably impossible without an archive node to calculate $ value)
- [ ] Uniswap LPs
- [ ] MakerDAO DSR ?

**Comment by LefterisJP** [comment]
This should be folded into #9457
