### ISSUE TITLE
Make asset movement inclusion optional with an accounting option

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#176]
## Problem Definition

History processing and tax report calculation at the moment always takes into account any asset movements from and to exchanges. Exchanges withdrawals always have fees and they are taken by default into account as a loss.

This should be made customizable.

## Tasks
![todo](https://user-images.githubusercontent.com/1658405/46442232-30432380-c769-11e8-95af-209620519083.png)

Add a new accounting option named `account_for_asset_movements`. 

- [ ] The location of the setting in the UI should be as shown in the screenshot above.
- [ ] The UI part should be done just like `include_crypto2crypto` is done. Source link [here](https://github.com/rotkehlchenio/rotkehlchen/blob/8ebed0ab3bc1bc61e38c1a88a1abfce0b47e2eb4/ui/accounting_settings.js#L94). Note: There is more places in the front-end code where it should be added.
- [ ] Pass the option to the backend and specifically to the accountant class as seen [here](https://github.com/rotkehlchenio/rotkehlchen/blob/8ebed0ab3bc1bc61e38c1a88a1abfce0b47e2eb4/rotkehlchen/accounting/accountant.py#L88) and as is also done for `include_crypto2crypto`.
- [ ] Use the option in the `add_asset_movement_to_events` function [here](https://github.com/rotkehlchenio/rotkehlchen/blob/8ebed0ab3bc1bc61e38c1a88a1abfce0b47e2eb4/rotkehlchen/accounting/accountant.py#L163).
