### ISSUE TITLE
Add ability for custom assets in manual balances along with custom price

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2021]
## Abstract

At the moment when adding a manual balance it has to be one of the supported assets. Which does not work really well all the time.

For example if you want to add an equity you would have to add it as EUR value directly. And it would show on the dashboard as EUR. Which is far from ideal. The end goal should be to have it all show on the dashboard with the unique name of the asset.

## Task

In order to achieve this we need the ability to:

- [ ] Add custom assets. Say a particular stock. Along with current prices for it. Related:
    * https://github.com/rotki/rotki/issues/1519
    * https://github.com/rotki/rotki/issues/1520
- [ ] In the manual balances section allow addition of custom assets too
- [ ] In the dashboard show all such assets

**Comment by LefterisJP** [comment]
Most of this should be done when we allow addition of custom assets (upgrade of custom tokens only from after v1.15.0).

**Comment by a7e8** [comment]
I would also like to see this feature added.

For shares and also real estate it currently shows as the currency they're priced in which is not ideal.

**Comment by LefterisJP** [comment]
> I would also like to see this feature added.
> 
> For shares and also real estate it currently shows as the currency they're priced in which is not ideal.

EXACTLY! This issue has kind of fallen in the sidelines but exactly what you describe here is the problem this issue wants to solve.

I track some ETFs with rotki, and manually update their price. That's not a problem.

But when my net value analysis is shown it bundles it up as EUR, which they are really not.

**Comment by a7e8** [comment]
In addition to this feature, which is really needed for manually tracking custom assets, I have another couple ideas which I will outline below.

For shares that are publicly listed, you might be better off looking up the prices using an API. For example if I have some TSLA shares I don't want to update the price manually each time I open Rotki. Now Rotki can do shares and crypto. Perhaps this is a follow on from this feature request.

Also it would be helpful to have the ability to categorise/filter the asset from the Dashboard view. Specifically I want to see just crypto on its own or everything for the total portfolio value & graph. This could be a simple toggle button to go between "All" and "Crypto" for example.

Lastly with the idea of custom assets it might be helpful to specify if they are liquid/illiquid. For example if you have some private shares that cannot be sold yet, they are illiquid assets. You might want to include them in your portfolio but again be able to view ALL assets or just liquid ones.

**Comment by MRobi1** [comment]
Is this still a manual process or is there a way to automate price updates for stocks and ETF's?

There's a gap to be filled right now for an all-in-one portfolio tracker that does both crypto and traditional investments. Ghostfolio sort of does it, but any transaction done which involves a currency conversion will have an inaccurate performance calculation which severely limits it's capabilities for a large amount of users.

**Comment by LefterisJP** [comment]
> Is this still a manual process or is there a way to automate price updates for stocks and ETF's?
> 
> There's a gap to be filled right now for an all-in-one portfolio tracker that does both crypto and traditional investments. Ghostfolio sort of does it, but any transaction done which involves a currency conversion will have an inaccurate performance calculation which severely limits it's capabilities for a large amount of users.

Still manual at the moment. We recognize the ability for automation here but lack of good APIs make it hard.

Would love any contributions in the form of Pull Requests if you have any cool ideas!

Can discuss further in our discord: https://discord.rotki.com/
