### ISSUE TITLE
Add support for historical view of blockchain account balances

### ISSUE THREAD

**Issue by nonsense** [rotki/rotki#2227]
## Abstract

At the moment it doesn't seem to be possible to specify a date/time and get your blockchain account balances based on a historical block (ETH, ERC20 tokens and DeFi). It'd be nice if somehow "Statistics" or "History" could show a historic view of your aggregate blockchain assets from your addresses.

## Motivation

This would be especially useful for folks who want to see a snapshot of their Ethereum balances on a specific date (i.e. 31.12.2020) and calculate their assets on that date.

## Specification

Given that Rotki already supports a variety of DeFi protocols, this would probably involves:

- [ ] ability to select date/time in a timepicker UI and determine the nearest block number for that timestamp
- [ ] fork from that block number and point Rotki to an ETH node that contains the state of Ethereum at that block number
- [ ] fetch prices for all assets at the given date/time - either via some DEX (Uniswap?) or maybe API to Coingecko?
- [ ] maybe cache historical results for all user's addresses, so that there is a graph (i.e. "Statistics" or "History") of change of balances from one day to the next (similar to dYdX Portfolio view).

## Open questions

I am not at all sure how that fits with the rest of the functionality that Rotki provides - i.e. exchange balances, and manual balances - obviously this functionality would be useful only for the assets held on Ethereum, but nevertheless I think it'd be a great feature to have.

**Comment by LefterisJP** [comment]
Hey @nonsense this is related to https://github.com/rotki/rotki/issues/1738 for querying the ethereum archive node.

Getting a solution both for people who have their own archive node (a very very small percentage of our userbase) and all others is what is hard to achieve.

Also the historical graph based on actual historical prices is a lot more involved as we don't just support ethereum but also other protocols and exchanges. The current graphs are made from balance snapshots for exactly that reason. A more generic solution would be what we plan to do for this issue: https://github.com/rotki/rotki/issues/1379

Just querying an address's balances and show historical prices for an ethereum address at a specific time would be a good possible first step and what I guess this issue could be kept for. Perhaps we can start this only for people who run their own node.

**Comment by gspoosi** [comment]
Gogo!

**Comment by LefterisJP** [comment]
I would change this issue to calculate the per address/location and total balances by processing history. And make another issue to perhaps for accounts we do have archive nodes for do a double check on that specific timestamp that the amount is correct.

**Comment by prettyirrelevant** [comment]
## implementation plan

rather than querying archive nodes for historical state, we compute balances from decoded history events. this approach works across all supported chains and doesn't require archive node access.
querying archive nodes for historical balances is tracked separately in #11283.

### schema
```sql
CREATE TABLE IF NOT EXISTS event_metrics (
    id INTEGER NOT NULL PRIMARY KEY,
    event_identifier INTEGER NOT NULL REFERENCES history_events(identifier) ON DELETE CASCADE,
    protocol TEXT,
    metric_key TEXT NOT NULL,
    metric_value TEXT NOT NULL,
    UNIQUE(event_identifier, protocol, metric_key)
);
```
### negative balance notification
when a negative balance is detected, send a websocket message so the user can investigate and fix the problematic event:
```json
{
    "event_identifier": 12345,
    "group_identifier": 12345,
    "asset": "ETH",
    "balance_before": "0.3",
    "timestamp": 1234567890,
    "last_run_ts": 1234567800
}
```

## progress
- [x] **event modification tracking** (#11214)
  - track `STALE_BALANCES_FROM_TS` in cache when events are added, edited, or deleted
  - this determines where balance recomputation should begin
- [x] **db schema and cache** (#11226)
  - add migration for `event_metadata` table
  - add `LAST_HISTORICAL_BALANCE_PROCESS_TS` cache to track when the task last completed
- [x] **background task implementation** (#11234)
  - when triggered, recompute balances from the earliest modified timestamp, inserting balance per event into the table
  - if a negative balance is detected, notify the user via websocket and stop
  - on success, update `LAST_HISTORICAL_BALANCE_PROCESS_TS`
  - synchronization needed to prevent concurrent execution with event-modifying background tasks (event decoding, protocol queries)
- [x] **HistoricalBalancesManager refactor** (#11251)
  - refactor methods to query the new table: `get_balances(timestamp)`, `get_asset_balance(asset, timestamp)`, `get_assets_amounts(assets, from_ts, to_ts)`, `get_historical_netvalue(from_ts, to_ts)`
- [x] **performance and endpoint improvements** (#11276, #11278, #11316)
  - remove price queries from historical balance endpoints
  - add support to retrieve historical net value as daily asset balances
  - add location filter to historical balance endpoints
- [x] **concurrency and edge case handling** (#11296, #11304, #11322)
  - handle concurrent modifications in balance processing
  - improve historical balance tracking for skipped and neutral events
  - fix possible race condition in `skip_if_running`
- [x] **distinguish defi protocol deposits from account deposits** (#11342, #11344, https://github.com/rotki/data/pull/244)
  - migrate defi protocol deposits to DEPOSIT_TO_PROTOCOL/WITHDRAW_FROM_PROTOCOL subtypes
  - add DB upgrade for deposit/withdrawal subtype migration
  - update data repo with new accounting rule
- [x] **support balance tracking for transfers and protocol deposits without wrapped tokens** (https://github.com/rotki/rotki/pull/11365, https://github.com/rotki/rotki/pull/11389)
  - either generate separate TRANSFER and RECEIVE events during decoding, or add a `location_label` column to event_metrics table (leaning towards the latter)
  - handle cases where protocol withdrawals exceed deposits (profit) without raising negative balance errors
- [x] **handle EURE asset upgrade in balance tracking** (https://github.com/rotki/assets/pull/314, https://github.com/rotki/rotki/pull/11408)
  - combine balances for old and new EURE during processing to avoid false negative balance errors
  - queries for either EURE version should return the combined balance

> [!CAUTION]
> the entire implementation was reverted in https://github.com/rotki/rotki/pull/11533 due to the issues described below amongst others.

> [!NOTE]
> the balance computation processes every event in the database regardless of the requested location/asset filter (e.g. kraken + eth). filtering only happens at query time against pre-computed buckets, so the results include unrelated data. this also affects the negative balances list (154 entries with no way to filter by location, account, or date) and the "show event" links (which surface many events rather than the specific problematic one). for more details see https://github.com/orgs/rotki/projects/11/views/3?pane=issue&itemId=153213724

**Comment by kelsos** [comment]
Follow-up focused on the **frontend / UI** for this. Draft mockups below (design drafts only, not final `@rotki/ui-library` styling, and the data is fabricated).

Two surfaces:

**1. Landing / index** — a net-value-over-time chart, the "as of" date picker with quick dates (year-ends, custom), and a short "how it works". Clicking a point on the chart, or picking a date, opens the breakdown.

<img width="1475" height="1625" alt="Image" src="https://github.com/user-attachments/assets/56a246e1-b379-47f0-b2d1-84ebb0ac3add" />

**2. Balances as of a date** — the breakdown itself:

<img width="1475" height="1625" alt="Image" src="https://github.com/user-attachments/assets/9d907591-ed61-4e54-a99e-561242ae9a4a" />

- **Grouped by asset**, each asset expandable to its per-bucket breakdown (the location: account, exchange, or protocol). Columns: Asset / location, Amount, Value, Reconciliation, plus a total row.
- **Value is filled in client-side** per historical price at the chosen date (the balance endpoints return amounts).
- **Date only** in the as-of control. A balances-at-date view spans multiple chains, each with its own block, so there's no single block number to show at the top.

**Reconciliation state per bucket** (shown as a small pill):

- `Reconciled` — the event-derived balance matches an independent source: the archive node for on-chain balances, or, for exchanges, the sum of history matching the current balance.
- `Verifying` — background check in progress.
- `Stale` — no source to verify against and possibly out of date, e.g. a balance left on a closed exchange (FTX) you imported and never fully withdrew.

At the **asset-total** level the aggregate can read `Partial` when part of the total sits on an unverifiable source, so the whole total isn't confirmed.

Two corrections to my earlier comment: live **exchanges are verifiable** (via current-balance consistency), and **aTokens are archive-verifiable** — so neither is blanket "not verifiable". Only balances with no source at all (closed venues, positions with no on-chain balance and no live balance) are `Stale`.

Deferred for a first cut: when your history can't explain an authoritative on-chain balance (a missing transaction), that isn't a reconciliation state, it's a data issue, and it should surface through the existing history **Data Issues / action items** inbox rather than a bespoke marker here.
