### ISSUE TITLE
Change the trade database and datastructure format to accept assets instead of a pair

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2243]
## Abstract

Related to #2240 (it does that only in the frontend part)

Change the backend DB schema for trades to accept individual assets and not a trade pair. This is going to be a big improvement as the legacy format of having a trade pair is much harder to work with as you need to always serialize to/from a pair each time you want to analyze a trade.

## Task

- [ ] Change the DB schema to accept assets instead of a pair string
- [ ] Change the data structure to use assets instead of a pair string
- [ ] Add a DB upgrade to upgrade all places where trades with a pair were used to the new schema. This needs A LOT of testing.
- [ ] Change all places in the code where the new schema needs to be used.

**Comment by LefterisJP** [comment]
Hmmm this was a wrong link auto-close
