### ISSUE TITLE
Investigate flakiness on e2e tests

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2255]
## Problem Definition

They have been flaky lately, there are two of them that fail

### Tasks
- [ ] Output backend logs on failure
- [x] Add delay on the manual balance test
- [x] Check the ignore tests
