### ISSUE TITLE
Premium users should be able to delete remote DB data

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2291]
## Abstract

Premium users have the ability to sync their local encrypted DB with the rotki server in order to keep offsite backups and/or transfer data between machines. If enabled this allows the user to upload their encrypted DB blob to the rotki server and to retrieve it from another machine.

At the same time there is no way to remove the data from the rotki server. If synchronization is turned off, the last data entry stays there until the user's premium runs out. This should change. Users should have full control over the remote DB data. Especially after https://github.com/rotki/rotki/issues/2287 which could have caused unwanted uploads to the server, users should be able to delete the data.

## Task

- [ ] Add a new premium api endpoint in the server for a user to delete their DB data saved in the server side
- [ ] Add a new api endpoint in the local app for premium users to delete the remote DB data
- [ ] Add another button in the UI for the user to delete the remote DB data. Question here is. Should this be in its own section or just another button where the user can download/upload DB data which would read "Delete" ?

**Comment by isidorosp** [comment]
I would also suggest that such an option should also be available/accessible via the "Manage Premium" page on the website as well.

**Comment by LefterisJP** [comment]
Though useful we will refactor a big part of the website and when we do this will go there probably. But for now it's important to be accessible from the app first and foremost.

**Comment by kelsos** [comment]
@yabirgb maybe we can schedule this for the next release.

Along with the app/api implementation we can also add a backup management section in the website where the users can delete/download their backups

**Comment by yabirgb** [comment]
> @yabirgb maybe we can schedule this for the next release.
> 
> Along with the app/api implementation we can also add a backup management section in the website where the users can delete/download their backups

Okey
