### ISSUE TITLE
Allow price oracle option that combines an average of multiple oracle results

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2308]
## Abstract

Follow up after https://github.com/rotki/rotki/issues/2131 and also 3rd point of  https://github.com/rotki/rotki/issues/1357

We can offer an option, that users query multiple oracles and take an average of all prices for the asset at a timestamp. This will be a much slower option for historical PnL and will also probably lead to rate limiting but can have the most accurate results and also find outliers/errors in a price oracle's prices.

## Task

- [ ] Add an option to combine price results from multiple oracles. Wonder how this can look in the frontend. Any ideas @kelsos?
- [ ] Implement the combination of prices from oracles and return of the average if the given setting is activated.
- [ ] Warn user if the price of any oracle for a given timestamp differs by a particular % from another. This way users can also detect outliers and errors in the prices given by the oracles.
