### ISSUE TITLE
Add price oracle exceptions per asset

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2309]
## Abstract

Users may want to add exceptions to the provided price oracle querying order for specific assets. The reason would most probably be mistaken prices for an asset from a price oracle.

## Task

- [ ] Implement different option for current and different for historical oracles.
- [ ] Add a setting which would be a mapping of assets to oracle orders. Make it customizable in the frontend.
- [ ] Use the setting in the backend when an oracle is queried for an asset. If the asset is in the exceptions use the order defined in the exception.
