### ISSUE TITLE
Allow input of custom rate for a ledger action

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2338]
## Abstract

At the moment ledger actions only involve an asset and a timestamp. The rate of the asset (in EUR, USD etc.) is not given. Instead it is taken from the historical price oracles.

But for some deals the rate may not be exactly that of an oracle and may indeed be pre-agreed with the counterparty. So we need to allow customization of the asset rate for a ledger action.

## Task

- [ ] Add a new optional field in all ledger actions, `asset_rate`. This will be essentially a tuple or a rate and another assets such as USD or EUR.
- [ ] If this rate is missing then calculate the rate as it is now by querying the price of the asset at the timestamp. If not, use the given rate of the ledger action
- [ ] In the UI add an opional field for users to fill in the asset rate.

**Comment by LefterisJP** [comment]
This will need a DB upgrade. So I will definitely include the DB upgrade right now in the work I am doing. Even if the final features does not make it in v1.16.0.

Even though it should be a pretty simple change from the UI side I guess @kelsos

**Comment by LefterisJP** [comment]
@kelsos in interest of documenting changes here, I would like to make one more small change which may affect the frontend a bit here.

I see that in both the `trades` table and in the `ledger_actions` table the `link`and `notes` attribute is not optional. And that if nothing is provided by the api we default to `''`.

Is it okay if I make it optional in the DB, and instead of `''` it returns None for missing/not set? For both fields in both structures.

**Comment by kelsos** [comment]
Sure go ahead.

**Comment by LefterisJP** [comment]
Fixed in develop by https://github.com/kelsos/rotki/commit/1b31f94bf6562a69431a935e523556c7ce028890 and frontend by: https://github.com/rotki/rotki/pull/2694

@kelsos: we forgot to close the issue in your frontend work. Also this issue should have been referenced in the changelog (instead of `-`). No worries I will do the small changelog change in my current PR.
