### ISSUE TITLE
Add docs entry about price oracles and how user can request cache building

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2367]
## Abstract

The concept of price Oracles may be foreign to some users so it requires explaining. There should be a section in the usage docs that explains it and makes them  able to understand where price history comes from. Also how to fix common problems with not being able to query price history.

## Task

- [x] Create a price oracles (both current and historical) entry in the usage guide.
- [x] Explain how they work and also include screenshots.
- [x] Provide common failure scenarios about historical price queries and what the user can do to amend them. For example if rotki shows an error that it can not find a historical price for an asset at a timestamp. Explain this may have happened due to rate limiting and that they can go to the price cache inspection module and request the cache for the pair to not have any problems in the future.
