### ISSUE TITLE
Allow premium users to import ETH2 daily staking details from beaconcha.in

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2379]
## Abstract

Related: https://github.com/rotki/rotki/issues/1993

Ideally these stuff will be automatically pulled via the API when it is properly exposed. But until that is done and to also save api calls we can allow premium users (since they only see the ETH2 staking view) to import data for each one of their validators from beaconchain.in

So for example for 33710 you go to https://beaconcha.in/validator/33710/stats and press "CSV"

![2021-02-16_01-46](https://user-images.githubusercontent.com/1658405/108005353-c9043200-6ff8-11eb-89b6-8bd3e936619b.png)

File looks like this:

```csv
"","Income","Start","End","M","O","P","M","O","Att","Prop","#","Amount"
"14 Feb 2021","+0.0081 ETH","32.62 ETH","32.63 ETH","0","0","-","-","-","-","-","-","0 ETH"
"13 Feb 2021","+0.0081 ETH","32.61 ETH","32.62 ETH","0","0","-","-","-","-","-","-","0 ETH"
"12 Feb 2021","+0.0082 ETH","32.6 ETH","32.61 ETH","0","0","-","-","-","-","-","-","0 ETH"
"11 Feb 2021","+0.0083 ETH","32.59 ETH","32.6 ETH","0","0","-","-","-","-","-","-","0 ETH"
"10 Feb 2021","+0.0084 ETH","32.59 ETH","32.59 ETH","0","0","-","-","-","-","-","-","0 ETH"
"09 Feb 2021","+0.0082 ETH","32.58 ETH","32.59 ETH","2","0","-","-","-","-","-","-","0 ETH"
"08 Feb 2021","+0.0082 ETH","32.57 ETH","32.58 ETH","0","0","-","-","-","-","-","-","0 ETH"
"07 Feb 2021","+0.0081 ETH","32.56 ETH","32.57 ETH","1","0","-","-","-","-","-","-","0 ETH"
"06 Feb 2021","+0.0083 ETH","32.55 ETH","32.56 ETH","1","0","-","-","-","-","-","-","0 ETH"
"05 Feb 2021","+0.0082 ETH","32.54 ETH","32.55 ETH","2","0","-","-","-","-","-","-","0 ETH"
"04 Feb 2021","+0.0116 ETH","32.53 ETH","32.54 ETH","1","0","1","0","0","0","0","-","0 ETH"
"03 Feb 2021","+0.0085 ETH","32.52 ETH","32.53 ETH","0","0","-","-","-","-","-","-","0 ETH"
"02 Feb 2021","+0.0084 ETH","32.52 ETH","32.52 ETH","1","0","-","-","-","-","-","-","0 ETH"
"01 Feb 2021","+0.0085 ETH","32.51 ETH","32.52 ETH","1","0","-","-","-","-","-","-","0 ETH"
"31 Jan 2021","+0.0088 ETH","32.5 ETH","32.51 ETH","0","0","-","-","-","-","-","-","0 ETH"
"30 Jan 2021","+0.0080 ETH","32.49 ETH","32.5 ETH","10","0","-","-","-","-","-","-","0 ETH"
"29 Jan 2021","+0.0088 ETH","32.48 ETH","32.49 ETH","0","0","-","-","-","-","-","-","0 ETH"
"28 Jan 2021","+0.0088 ETH","32.47 ETH","32.48 ETH","1","0","-","-","-","-","-","-","0 ETH"
"27 Jan 2021","+0.0088 ETH","32.46 ETH","32.47 ETH","1","0","-","-","-","-","-","-","0 ETH"
"26 Jan 2021","+0.0091 ETH","32.46 ETH","32.46 ETH","0","0","-","-","-","-","-","-","0 ETH"
"25 Jan 2021","+0.0092 ETH","32.45 ETH","32.46 ETH","0","0","-","-","-","-","-","-","0 ETH"
"24 Jan 2021","+0.0093 ETH","32.44 ETH","32.45 ETH","0","0","-","-","-","-","-","-","0 ETH"
"23 Jan 2021","+0.0092 ETH","32.43 ETH","32.44 ETH","0","0","-","-","-","-","-","-","0 ETH"
"22 Jan 2021","+0.0092 ETH","32.42 ETH","32.43 ETH","0","0","-","-","-","-","-","-","0 ETH"
"21 Jan 2021","+0.0093 ETH","32.41 ETH","32.42 ETH","0","0","-","-","-","-","-","-","0 ETH"
"20 Jan 2021","+0.0091 ETH","32.4 ETH","32.41 ETH","3","0","-","-","-","-","-","-","0 ETH"
"19 Jan 2021","+0.0095 ETH","32.39 ETH","32.4 ETH","0","0","-","-","-","-","-","-","0 ETH"
"18 Jan 2021","+0.0095 ETH","32.38 ETH","32.39 ETH","0","0","-","-","-","-","-","-","0 ETH"
"17 Jan 2021","+0.0097 ETH","32.37 ETH","32.38 ETH","0","0","-","-","-","-","-","-","0 ETH"
"16 Jan 2021","+0.0098 ETH","32.36 ETH","32.37 ETH","0","0","-","-","-","-","-","-","0 ETH"
"15 Jan 2021","+0.0098 ETH","32.35 ETH","32.36 ETH","0","0","-","-","-","-","-","-","0 ETH"
"14 Jan 2021","+0.0099 ETH","32.34 ETH","32.35 ETH","0","0","-","-","-","-","-","-","0 ETH"
"13 Jan 2021","+0.0126 ETH","32.33 ETH","32.34 ETH","0","0","1","0","0","0","0","-","0 ETH"
"12 Jan 2021","+0.0100 ETH","32.32 ETH","32.33 ETH","0","0","-","-","-","-","-","-","0 ETH"
"11 Jan 2021","+0.0102 ETH","32.31 ETH","32.32 ETH","0","0","-","-","-","-","-","-","0 ETH"
"10 Jan 2021","+0.0102 ETH","32.3 ETH","32.31 ETH","0","0","-","-","-","-","-","-","0 ETH"
"09 Jan 2021","+0.0129 ETH","32.29 ETH","32.3 ETH","0","0","1","0","0","0","0","-","0 ETH"
"08 Jan 2021","+0.0104 ETH","32.28 ETH","32.29 ETH","0","0","-","-","-","-","-","-","0 ETH"
"07 Jan 2021","+0.0104 ETH","32.27 ETH","32.28 ETH","0","0","-","-","-","-","-","-","0 ETH"
"06 Jan 2021","+0.0105 ETH","32.25 ETH","32.27 ETH","0","0","-","-","-","-","-","-","0 ETH"
"05 Jan 2021","+0.0105 ETH","32.24 ETH","32.25 ETH","0","0","-","-","-","-","-","-","0 ETH"
"04 Jan 2021","+0.0133 ETH","32.23 ETH","32.24 ETH","0","0","1","0","0","0","0","-","0 ETH"
"03 Jan 2021","+0.0107 ETH","32.22 ETH","32.23 ETH","0","0","-","-","-","-","-","-","0 ETH"
"02 Jan 2021","+0.0109 ETH","32.21 ETH","32.22 ETH","0","0","-","-","-","-","-","-","0 ETH"
"01 Jan 2021","+0.0110 ETH","32.2 ETH","32.21 ETH","0","0","-","-","-","-","-","-","0 ETH"
"31 Dec 2020","+0.0111 ETH","32.19 ETH","32.2 ETH","0","0","-","-","-","-","-","-","0 ETH"
"30 Dec 2020","+0.0137 ETH","32.17 ETH","32.19 ETH","0","0","1","0","0","0","0","-","0 ETH"
"29 Dec 2020","+0.0113 ETH","32.16 ETH","32.17 ETH","0","0","-","-","-","-","-","-","0 ETH"
"28 Dec 2020","+0.0114 ETH","32.15 ETH","32.16 ETH","0","0","-","-","-","-","-","-","0 ETH"
"27 Dec 2020","+0.0139 ETH","32.14 ETH","32.15 ETH","0","0","1","0","0","0","0","-","0 ETH"
"26 Dec 2020","+0.0117 ETH","32.13 ETH","32.14 ETH","0","0","-","-","-","-","-","-","0 ETH"
"25 Dec 2020","+0.0117 ETH","32.11 ETH","32.13 ETH","0","0","-","-","-","-","-","-","0 ETH"
"24 Dec 2020","+0.0119 ETH","32.1 ETH","32.11 ETH","0","0","-","-","-","-","-","-","0 ETH"
"23 Dec 2020","+0.0120 ETH","32.09 ETH","32.1 ETH","0","0","-","-","-","-","-","-","0 ETH"
"22 Dec 2020","+0.0121 ETH","32.08 ETH","32.09 ETH","1","0","-","-","-","-","-","-","0 ETH"
"21 Dec 2020","+0.0124 ETH","32.07 ETH","32.08 ETH","0","0","-","-","-","-","-","-","0 ETH"
"20 Dec 2020","+0.0144 ETH","32.05 ETH","32.07 ETH","1","0","1","0","0","0","0","-","0 ETH"
"19 Dec 2020","+0.0127 ETH","32.04 ETH","32.05 ETH","0","0","-","-","-","-","-","-","0 ETH"
"18 Dec 2020","+0.0129 ETH","32.03 ETH","32.04 ETH","0","0","-","-","-","-","-","-","0 ETH"
"17 Dec 2020","-0.0001 ETH","32.03 ETH","32.03 ETH","126","0","-","-","-","-","-","-","0 ETH"
"16 Dec 2020","+0.0132 ETH","32.01 ETH","32.03 ETH","0","0","-","-","-","-","-","-","0 ETH"
"15 Dec 2020","+0.0120 ETH","32 ETH","32.01 ETH","0","0","1","0","0","0","0","-","0 ETH"
"14 Dec 2020","0.0000 ETH","32 ETH","32 ETH","-","-","-","-","-","-","-","-","0 ETH"
"13 Dec 2020","0.0000 ETH","32 ETH","32 ETH","-","-","-","-","-","-","-","-","0 ETH"
"12 Dec 2020","0.0000 ETH","32 ETH","32 ETH","-","-","-","-","-","-","-","-","0 ETH"
"11 Dec 2020","0.0000 ETH","32 ETH","32 ETH","-","-","-","-","-","-","-","-","0 ETH"
"10 Dec 2020","0.0000 ETH","32 ETH","32 ETH","-","-","-","-","-","-","-","-","0 ETH"
"09 Dec 2020","0.0000 ETH","32 ETH","32 ETH","-","-","-","-","-","-","-","-","0 ETH"
"08 Dec 2020","0.0000 ETH","32 ETH","32 ETH","-","-","-","-","-","-","-","-","0 ETH"
"07 Dec 2020","0.0000 ETH","32 ETH","32 ETH","-","-","-","-","-","-","-","-","0 ETH"
"06 Dec 2020","0.0000 ETH","32 ETH","32 ETH","-","-","-","-","-","-","-","-","0 ETH"
"05 Dec 2020","0.0000 ETH","0 ETH","32 ETH","-","-","-","-","-","-","-","1","+32.0000 ETH"
```

We are only interested in the 1st and 2nd columns I suppose.

## Task

- [ ] Implement the import api endpoint
- [ ] Save the data in the DB
- [ ] Take it into account in the PnL report using ETH price at the day close.
- [ ] Implement the import functionality in the frontend
- [ ] Show these data in the frontend too once imported.
