### ISSUE TITLE
Improve auto-updater experience

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#2424]
## Abstract

While testing the auto-updater on macos I realized that in some cases it is not overly clear what is happening.
To improve the overall experience the following should be done:

### Tasks 

- [x] Show download progress when the file is downloaded
- [x] Redirect logging of electron-updater to the `rotki-electron.log`
- [x] Properly notify the user when the download fails for any reason (e.g macos read-only dmg)
