### ISSUE TITLE
Add ability to clean DB from eth2 daily stats and eth2 deposits

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2520]
## Abstract

At the moment we have a [method](https://github.com/rotki/rotki/blob/1dd5ba9feb8aa81d6b5a5e177a2802aa25e01c3e/rotkehlchen/db/eth2.py#L56) to delete eth2 deposits, but no method to delete eth2 daily stats.

Additionally there is no way for those to be called by the user to clean their DB after a quick look. So this should be addressed.

Make sure to also clean the `used_query_ranges` for the address, if cleaning by address and all of them if cleaning all of eth2.

```python
        cursor.execute(
            f'DELETE FROM used_query_ranges WHERE name="{ETH2_DEPOSITS_PREFIX}_{address}";',
        )
```

## Task

- [ ] Add the necessary backend code
- [ ] Add API endpoint exposure
- [ ] Make it callable by the frontend UI

**Comment by LefterisJP** [comment]
> Why is it necessary to also delete the used_query_ranges to delete daily stats?

It's not. The issue says: 

> Make sure to also clean the used_query_ranges for the address, if cleaning by address and all of them if cleaning all of eth2.

And the code in the example mentions deposits.

> Also I don't see a call to the existing method... is it used?

Nope. That's the point. We need to expose it in some way to the frontend. Perhaps through the purge module data function, and make eth2 another module (which would make sense).

And that function should now also delete the daily stats, not just the deposits.

**Comment by yabirgb** [comment]
@LefterisJP I see it fine adding eth2 as a module but the `purge_module_data` function at the moment doesn't make any distinction about what you are deleting, so to delete data for only one address this information should also be passed

**Comment by LefterisJP** [comment]
Do you mean something like this function? https://github.com/rotki/rotki/blob/c6883dbe5487befb997e0dfc559034f481f98a82/rotkehlchen/db/dbhandler.py#L2604-L2663

We delete per address information for everything when an address is removed.
