### ISSUE TITLE
Guard against deletion of assets from GlobalDB if owned by any users

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2524]
## Problem Definition

At the moment it's possible for a user to delete an asset from the GlobalD and if any other local user has this asset problems will arise. 

We have to guard against this.

It's a bit more complicated since there is one global DB and there can be many users. But the end result should be that if any user owns any assets that is being deleted from the GlobalDB then deletion should fail.

# Task

There are many ways to achieve this. One that I have thought of is:

- [ ] Add a new table in global db called user_owned_assets, with just one key the identifier, which is a foreign key to asset identifier. No user identifier there to not leak user data in case of multiple users. Still we leak some, but not too much data if someone has access to the user machine.
- [ ] Every time a user logs in, all their owned assets should be `INSERT or IGNORE` in the new table of the global DB. Every time a new asset is added, the same thing should happen.
- [ ] At GlobalDB deletion provide an appropriate error message if this particular foreign key constraint hits.
