### ISSUE TITLE
Provide way to add support for new assets with the new GlobalDB methodology

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2551]
## Abstract

Once https://github.com/rotki/rotki/issues/2550 is implemented we still need a way to be able to add new assets or provide edits for old assets and have them included in the local Global DB of the user.

## Task

- [ ] Keep a list of all assets (non eth tokens. Eth tokens **should not** be added until v1.16.0) that were added since v1.15.0 in case we need to think of a specific upgrade for them.
    - (fiat) TWD: https://github.com/rotki/rotki/pull/2563
- [ ] Figure out a scheme for the global DB to remember when it was last updated and with which remote update
- [ ] Figure out an easy way for users/other devs to create remote updates for the DB. In the end it should be (or compile down to) a number of sqlite statements.
- [ ] These upgrades will not be applied automatically. Instead of that Api endpoints should be added that will:
    - [ ] Detect if there is any such upgrades and how many they are
    - [ ] Download and apply them to the user's Global DB. During addition gather any conflicts and return them with some kind of identifier to the user
    - [ ] The user will then be able to select how to resolve each conflict.
- [ ] Frontend UI for the above

**Comment by LefterisJP** [comment]
As per our standup discussion @kelsos this is just a rough idea of how the api can look:

### Check for updates

`GET /assets/updates`

async_query: True/False (since it contains remote calls)

Returns

```json
{
    "local_version": 1,
    "remote_version": 5,
}
```
### Ask for update

`POST /assets/updates`

async_query: True/False since it will require a remote call.

I guess here irrespective of the result of the `GET`, if you call post it will try to do an upgrade.

(Does that make sense? -- I think yes but wonder what's your opinion)

This will return for success:

```json
{
    "result": true,
    "message": ""
}
```

In case of conflicts it will return:
```
{
    "result": [{
        "identifier":  "assetid1",
        "local": {
            "coingecko": "2give",
            "name": "2GIVE",
            "started": 1460937600,
            "symbol": "2GIVE",
            "type": "own chain"
        },
        "remote": {
            "coingecko": "TWOgive",
            "name": "TWOGIVE",
            "started": 1460937600,
            "symbol": "2GIVEORNOTTOGIVE",
            "type": "own chain"
       }}, {
       "identifier": "asset_id2",
       "local": {
               "coingecko": "aave",
               "ethereum_address": "0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9",
               "ethereum_token_decimals": 18,
               "name": "Aave Token",
               "started": 1600970788,
               "symbol": "AAVE",
               "type": "ethereum token"
       },
       "remote": {
               "coingecko": "aaveNGORZ",
               "ethereum_address": "0x1Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9",
               "ethereum_token_decimals": 15,
               "name": "Aave Token FOR REALZ",
               "started": 1600970789,
               "symbol": "AAVE_YO!",
               "type": "binance token"
       } 
    }],
    "message": ""
}
```

In case of conflict you are supposed to take the conflict assets ids and specify how to solve them by doing another `POST` on the same endpoint.


```POST /assets/updates

{
    "async_query": true/false,
    "conflicts": {"assetid1": "local", "assetid2": "remote"}
}
```

If not all conflicts are contained then the backend will again respond with conflicts.
