### ISSUE TITLE
Add per-user notes

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2607]
## Abstract

A user has requested this feature. The idea is simple. They want to be able to add notes for their portfolio tracking and accounting and keep them also encrypted in the same place as the rest of the data.

The use case is for things like manual balances,manual entries they may have to create due to extraneous circumstances such as using a not yet supported exchange in rotki.

The frontend component should be somewhere where it can be accessed in all views. So probably some kind of dropdown text field editing from the top left or the top right of the menu?

## Task

- [ ] Implement a per user notes text field in the DB
- [ ] Implement API endpoints to get its contents, or replace its contents
- [ ] Add the frontend component to manipulate the text field

**Comment by isidorosp** [comment]
+1 to this, I've recently been keeping like a small set of notes with regards to things I need to remember to track (e.g. assets in staked contracts that rotki doesn't read) and I would love if I could keep that info _in_ rotki. Request: from a frontend perspective: would be great if this supported markdown!

**Comment by nonsense** [comment]
+1 Adding a note alongside entries added under `manual balances` would be a great feature.

**Comment by LefterisJP** [comment]
Let's do this. But let's find a good place in the frontend (for UX reasons) to have it. It's really an easy feature and would be a good plus to have.
