### ISSUE TITLE
Figure out a way to get rid of the majority of global constant assets

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2751]
## Abstract

With a dynamic database of assets it's ill-advised to have global constant assets defined in the code, apart from maybe the most basic of the basic, like ETH, BTC etc.

The reason for this is simple.

1. If a user has not yet updated their DB to get a new asset and the asset is used as a constant somewhere ... BOOM when the app starts.
```
2021-04-18T22:53:38.550Z: Determining if we are packaged by seeing if /home/lefteris/w/rotkehlchen/frontend/app/node_modules/electron/dist/resources/rotkehlchen_py_dist exists
2021-04-18T22:53:38.550Z: Starting non-packaged python subprocess: python -m rotkehlchen --api-port 4242 --api-cors http://localhost:8080 --logfile /home/lefteris/.config/rotki/logs/rotkehlchen.log --loglevel debug
2021-04-18T22:53:38.555Z: The Python sub-process started on port: 4242 (PID: 89894)
2021-04-18T22:53:39.456Z: Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/__main__.py", line 8, in <module>
    from rotkehlchen.server import RotkehlchenServer
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/server.py", line 7, in <module>
    from rotkehlchen.api.server import APIServer, RestAPI
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/server.py", line 16, in <module>
    from rotkehlchen.api.rest import RestAPI, api_response, wrap_in_fail_result
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/rest.py", line 31, in <module>
    from rotkehlchen.accounting.ledger_actions import LedgerAction
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/accounting/ledger_actions.py", line 8, in <module>
    from rotkehlchen.serialization.deserialize import (
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/serialization/deserialize.py", line 8, in <module>
    from rotkehlchen.assets.utils import get_asset_by_symbol
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/assets/utils.py", line 4, in <module>
    from rotkehlchen.constants.assets import A_ETH
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/constants/assets.py", line 110, in <module>
    A_CRV_A3CRV = EthereumToken('0xFd2a8fA60Abd58Efe3EeE34dd494cD491dC14900')
  File "<string>", line 4, in __init__
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/assets/asset.py", line 405, in __post_init__
    super().__post_init__(form_with_incomplete_data)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/assets/asset.py", line 300, in __post_init__
    data = AssetResolver().get_asset_data(self.identifier, form_with_incomplete_data)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/assets/resolver.py", line 57, in get_asset_data
    raise UnknownAsset(asset_identifier)
rotkehlchen.errors.UnknownAsset: Unknown asset _ceth_0xFd2a8fA60Abd58Efe3EeE34dd494cD491dC14900 provided.
2021-04-18T22:53:39.456Z: The Python sub-process exited with signal: null (Code: 1)
2021-04-18T22:54:05.391Z: Terminating the backend
```
2. If a user deletes an asset that is used as a constant somewhere ... BOOM!

(1) won't be always so obvious as it was in develop. We start by reading the shipped DB, which would have all assets, but then switch to the user's DB which may not. The difference after the switch can lead to a ton of funny behavior.

To avoid that for now and the for any new constants we can only avoid declaring them as constants as can be seen in this small PR: https://github.com/rotki/rotki/pull/2750/files

We need to figure out a solution to this

## Task

Figure out a solution. A way to (1) get rid of as many of the global asset constants as possible and also for the ones that stay, have them lazily evaluated and/or handle UnknownAsset errors gracefully.

**Comment by LefterisJP** [comment]
I will pick this up for this release. I think I know how

**Comment by LefterisJP** [comment]
We should initialize all assets from fields without reading from the DB as enabled by the changes in this PR: https://github.com/rotki/rotki/pull/3060

What should be done is:

- [ ] Allow initialization of assets by field (just like the code does now with tokens)
- [ ] Change all constant asset declarations to use fields initialization. Try to reduce numbers of constant assets used in production. For tests .. we don't care. It can still use the DB initialization (by identifier)
- [ ] Write a test that takes all constants declared in production and makes sure they are the same as the ones in the globaldb we are including with the app.
- [ ] Figure out all the places where this change will allow us to change/improve things and make issues for them.
