### ISSUE TITLE
Move more common types to the common library

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#3240]
## Abstract

Followup to #3202 

### Tasks
- [ ] Move Aave types
- [ ] Move Balancer types
- [ ] Move AdEx types
- [ ] Move Eth2 staking types
- [ ] Move Uniswap types
