### ISSUE TITLE
Query, persist and show avalanche transactions in the UI

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3256]
## Abstract

As a follow up from https://github.com/rotki/rotki/issues/2971 and its implementation (https://github.com/rotki/rotki/pull/3242/) we will need to also query and persist the tracked account transactions in the database and also show them in the frontend just like we do with ethereum transactions.

## Task

- [ ] Query the avalanche transactions. There is already code for this
- [ ] Add a DB Schema for avalance transactions. If identical with EVM, perhaps enhance existing table via a DB upgrade with a chain id.
- [ ] Show the avalanche transactions in the frontend
- [ ] If possible once we implement the nice readable form of transaction decoding for ethereum use that too for avalanche. Can be another issue/PR: https://github.com/rotki/rotki/issues/1477

**Comment by LefterisJP** [comment]
Finally a user asked for this feature. So let's think of how to make Avalanche like the rest of the EVM chains.
