### ISSUE TITLE
Make virtual zero amounts in balance snapshots configurable

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3576]
## Problem Definition

The way https://github.com/rotki/rotki/issues/2613 was solved has introduced an additional problem. We now return `N` zero virtual balance between every 2 saved snapshots if their time difference is `N`x 24 hours.

This manifests in quite broken asset graphs for most users.

![136640664-0c734d8c-91db-47bf-8467-f69ef64f8d31](https://user-images.githubusercontent.com/1658405/136648356-e6f21811-4584-4497-9e13-449094168e4e.jpg)

Was assuming a 24 hours regular snapshot saving when coding the solution. But I did not take into account few very important factors:

1. The saving snapshot frequency is configurable
2. Snapshot is not saved every `snapshot_frequency`  hours unless the user restarts the app. (issue: https://github.com/rotki/rotki/issues/1106)
3. Due to (2) if the user restarts after says 2 days then a new snapshot is taken then. But the snapshot diff is more than 24 hours so a 0 balance is put in between.

## Task

There really is no elegant solution to this. We can improve this, but we also need to make it configurable and even allow disabling.

- [x] Introduce a new setting. This will be a multiplier (float) to the selected snapshot saving frequency. Can also be zero. Default should be 0
- [x] Change the zero snapshot addition implementation made for #2613 to add the 0 snapshot only if the difference between snapshots is equal to the multiplier multiplied by the snapshot frequency.
- [x] If multiplier is zero, completely ignore these virtual zero snapshots and return data as is. So as was before v1.21.1

One caveat of this entire approach is (2) in the description above and that the saving frequency is not constant and can be changed. That's why with multiplier zero we can at least remove this feature.

**Comment by LefterisJP** [comment]
Should be fixed by #3597 and #3601
