### ISSUE TITLE
Support Apple Silicon

### ISSUE THREAD

**Issue by dmihal** [rotki/rotki#4067]
I went to install Rotki on my new Macbook, however I can't run the program without installing Rosetta (which I'd like to avoid).

Would be great if the Mac build included support for Apple Silicon chips (I believe these are called universal binaries)

**Comment by eis2k** [comment]
+1 
the last app on my m1 that needs Rosetta

**Comment by kelsos** [comment]
> I went to install Rotki on my new Macbook, however I can't run the program without installing Rosetta (which I'd like to avoid).
> 
> Would be great if the Mac build included support for Apple Silicon chips (I believe these are called universal binaries)

Yes, it seems that they are called universal binaries indeed.

For electron there is https://github.com/electron/universal which we would have to integrate into our build processes for macOS

PyInstaller also seems to support universal binaries, at least from what I can see in the 4.8 changelog.

## TODO

To build the universal binaries we need:

- [ ] Use the MacOS 11 runner on GitHub Actions _(We currently use 10.15 because the 11 runner would create binaries that would not run on Mojave, the earliest version we support. This is related to the miniupnpc library)_
- [ ] Make use of Electron Universal (see what changes are needed to our CI process)
- [ ] Make PyInstaller create a universal binary that will be bundled with the Electron app (see what changes are needed to our CI process)

The biggest hurdle to natively support M1 macs at the moment though, assuming that we disable miniupnpc or work around the incompatibility on Mojave is that there is no way to debug/test the process since none of the developers has access to an M1 Mac.

**Comment by LefterisJP** [comment]
> The biggest hurdle to natively support M1 macs at the moment though, assuming that we disable miniupnpc or work around the incompatibility on Mojave is that there is no way to debug/test the process since none of the developers has access to an M1 Mac.

Very happy to say that thanks to @Clearwood this issue will go ahead faster as he has donated 1k USDT which has already been put towards ordering a Mac Mini M1 so we can test and develop all the changes required to get this implemented for you guys: https://twitter.com/LefterisJP/status/1491417570775560193

What's more this will be the rotki team's first actual MacOS hardware so I expect debugging MacOS issues to be easier now. So far for all MacOS specific issue we were using VMs.

**Comment by kelsos** [comment]
This will be scheduled for the next feature release. We now have access to an M1 mac mini, and I already did some preliminary investigation, on what we need to do. 

It seems that some of the problems in building the app on the Mac mini seem similar to the issues we encountered with pysqlchiper3 when building for Windows. 

As soon as we are done with 1.24 I should be able to pick this up.
