### ISSUE TITLE
Change the flow of publishing docker build to update latest after publishing a release

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#4336]
## Abstract

Users might depend on the `latest` tag to update their containers, e.g. auto-updating using watchtower. 

With the current release flow, `latest` is updated as soon as the build finishes.
Sometimes this might be too early as last moment bugs might be detected, and users might update to broken builds.

We should only update the latest tag on release.

### TODO
- [ ] Keep a tag updated on build to make testing possible. 
- [ ] See if there is a way to re-tag an existing image on docker without re-build
- [ ] Add a github action??? that updates latest on release

**Comment by kelsos** [comment]
We can use a pinned version of `regctl` from [regclient](https://github.com/regclient/regclient) in order to update `rotki/rotki:latest` on release with an extra action/flow on GitHub Actions.

I used this to fix the accidental update and it worked fine.

@LefterisJP what I was thinking is to create the tagged version e.g. v1.25.0 and push it normally on docker hub since we need to test it anyway and the user's would have to manually pull it before release for it to pose any problem, and then on release just update latest from this.

The command would be something like `/regctl-linux-amd64 image copy rotki/rotki:v1.25.0 rotki/rotki:latest`

**Comment by LefterisJP** [comment]
If it can be automated let's do that

**Comment by kelsos** [comment]
> If it can be automated let's do that

It can. I can have a GitHub Actions flow that gets triggered on [release/publish](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release) which can run the `regctl` command.
