### ISSUE TITLE
Frontend changes meta issue

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#4872]
## Abstract

I have a few things in mind that we should do in the frontend.
This is a meta issue to keep track of and proceed with. **We can create and link issues when needed.**

## Motivation

Improve the day-to-day situation (linting/editor performance) etc.

## Specification

- [x] Split `rotkehlchen-api` to smaller utility classes  https://github.com/rotki/rotki/blob/172c1ad9d055200eeeeb6dd93e4f063739f9b9e8/frontend/app/src/services/rotkehlchen-api.ts#L73 (#5259) (#5578)

> An example of the approach can be found here:
https://github.com/rotki/rotki/blob/172c1ad9d055200eeeeb6dd93e4f063739f9b9e8/frontend/app/src/services/session/queried-addresses-api.ts#L13

- [x] Try to keep typescript files around ~20 imports ~400loc (check if there is an ESLint plugin for that) 
- [x] Slowly convert components to use `setup` (ESLint now warns but it will turn to an error when this is done.)
- [x] move any exported type, utility classes, and consts out of the `/composables` and `stores` directories. (When done we can enable auto-import for these)(#5571)
- [x]  Finish removing the `keys` approach for auto conversion of strings to BigNumber and replace all cases with zod schemas (balance keys have been marked as deprecated (#5220)
- [x] Introduce layouts with [vite-plugin-vue-layouts](https://github.com/JohnCampionJr/vite-plugin-vue-layouts), split loading/login/account creation to different views
- [x] Evaluate if it makes sense to at some point migrate to [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages) #5075
- [x] Replace usage of vuetify validation using `rules` with vuelidate (#5230)
- [x] Check if it makes sense to move to `pnpm` (#5237).
- [x] Update to unified confirmation dialog (#5249)

> I will add more stuff in the future but this is just to keep track of things
@lukicenturi if you also have any ideas please add them here.

**Comment by kelsos** [comment]
There are some problems with `vite-plugin-pages` for our use-case, but the views have been renamed go pages and they follow a similar structure.

After updating to vue 3 and vue-router 4.x we can instead move to [unplugin-vue-router](https://github.com/posva/unplugin-vue-router) which uses a similar folder structure as the pages plugin and has some generation for routes that would actually help.

**Comment by kelsos** [comment]
I started this with the multi evm addition but we can now slowly start:

- [ ] Start moving `use*Api` composables to `app/src/composables/api`

**Comment by kelsos** [comment]
I am gonna consider this meta issue closed for the time being

We still need to take care of the imports/loc part but we have the warning enabled so no reason to keep this issue open anymore just for this
