### ISSUE TITLE
Sanity checks for DB schema

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#5077]
## Abstract

We have been bitten multple times by DB upgrades where something was not as expected at the user's DB due to some kind of error that probably happened or due to having a botched nightly version or due to being manually edited ... or ... or .... or

And we always end up noticing at the last possible moment. At the time of the DB upgrades.

We can improve on this

## Task

- [ ] Create a sanity check for the user DB that checks all tables, all view and their schemas and makes sure they are all correct, all there as expected and there is nothing extra.
- [ ] Do the same for the global DB
- [ ] Run these sanity checks at app's startup
- [ ] If for whatever reason they fail, inform the user with as much info as possible and ask them to file a bug report

**Comment by nebolax** [comment]
Completed in #5091
