### ISSUE TITLE
Enforce smaller transactions and single transaction per connection. Undo auto-savepoints.

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#5222]
## Abstract

In order to make things more explicit in how transactions are handled and fix bugs that happened, especially in DB upgrades, in https://github.com/rotki/rotki/pull/5203 we switched to using `isolation_level=None` and stop using the default python sqlite auto-commit mode.

Each write_ctx right now opens a transaction explicitly and closes it when going out, either normally or via an exception.

There is many places where we have multiple nested write_ctx()s in the codebase right now. Opening another transaction while one is progress is a BOOM-able offense.

In order to facilitiate for that and not make too many changes that PR cheats, by making any subsequently nested write_ctx actually open a savepoint under the hood.

This works fine, for 99% of the cases, but has some edge cases. These edge cases would be bad design on our part and they would not be noticed easily. Say three nested write contexts, with the 3rd commiting and the 2nd rolling back. The 3rd would also be rolled back since they were nested. And nesting may also come inadvedertedly through accessing the connection via different greenlets.

In order to get rid of all these we should keep things explicit.

## Task

- [x] Modify the write_ctx code to only do a single transaction and disallow opening a 2nd one. If trying to open a 2nd one it should wait/lock until the first one is finished. Remove the explicit savepoint logic.
- [x] Nested savepoints should work as they already do BUT only be used explicitly with the savepoint_ctx. (nothing actionable here I think -- just writing it to make it clear)
- [x] Go through code thanks to tests, and opening the app. Find all write_ctx usage that is wrong and fix it. Make sure we don't open a write_ctx without a reason, keep it as short as possible, and that it does not nest. If nesting is needed, with specific part rollback-able then this is exactly where savepoints should explicitly be used.
