### ISSUE TITLE
Be able to run Rotki in a headless machine like Avado/Dappnode

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#523]
## Abstract

It would be nice to be able to run Rotki in a headless machine as explained in the discussion of  [this](https://github.com/rotkehlchenio/rotkehlchen/issues/521#issue-508972339) issue so that it can run on Dappnode/Avado Server among other things.

## Task

This is a meta issue which will require the completion of the following sub-issues:

- [x] [Have a dockerized version of Rotki](https://github.com/rotkehlchenio/rotkehlchen/issues/521) 
- [x] [Replace zerorpc with a normal webserver](https://github.com/rotkehlchenio/rotkehlchen/issues/404)
- [x] [Allow Rotki frontend to connect to a backend running in another machine](https://github.com/rotkehlchenio/rotkehlchen/issues/522)
- [x] [Update endpoints and frontend to upload/download files outside of electron](https://github.com/rotki/rotki/issues/1611)
- Also check the places that we use links. most of them should work outside of electron in the same way but it would be better to make sure.

**Comment by kelsos** [comment]
@LefterisJP We should also evaluate if it is possible (it should be) to run this version without any need for electron directly from the browser.

**Comment by LefterisJP** [comment]
@kelsos What would that require? Shouldn't be that hard to achieve, right? Essentially it should all work from the browser too.

**Comment by kelsos** [comment]
Some parts might not work in the browser. For example, any node filesystem interactions might need some different handling in the browser. eg. CVS export of the report in the browser should be treated as a download.

**Comment by LefterisJP** [comment]
Yeah that makes sense. But the first step would be to make the electron app connect to the backend in another machine and then we can see about browser support. As you point out there is gonna be subtle differences so we should go step by step.

**Comment by froid1911** [comment]
Hello everyone,
i just setup my dappnode and dont have much time, but i want to push this issue and contribute. 
anything I can do?

**Comment by LefterisJP** [comment]
Hey @froid1911 the first thing we need done for this is to allow rotki to run in a docker with all features exposed. That means to run in a browser and not electron. The one issue remaining for this is to update our code (both backend and frontend) to work with file upload and download when it's not electron, instead of using the filesystem: https://github.com/rotki/rotki/issues/1611

**Comment by LefterisJP** [comment]
@kelsos what is the status here? Have you not already competed all the steps for this? What is missing?

**Comment by kelsos** [comment]
@LefterisJP Well we have this point to connect to a custom different backend do we want it currently or is it out of scope for this issue?

**Comment by LefterisJP** [comment]
I guess we want it. What is missing for this? Is it a lot of work?

**Comment by kelsos** [comment]
It shouldn't be much I will pick it up after finishing with the existing issues so we can completely close this
