### ISSUE TITLE
Querying trades of a single exchange that is ignored for sync should not pull data

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#5265]
## Problem Definition

rotki has a setting for each CEX that is meant to ignore syncing data with that exchange. The problem is that in the trades querying view, the frontend asks trades for each exchange separately.

In our code the function that decides whether data needs to be pulled from the exchange respects the setting when it concerns all exchanges (it iterates only connected exchanges that are not ignored), but not when querying a single one directly.

https://github.com/rotki/rotki/blob/62540a0e094b4bf9f5be87876b84dae99dc31300/rotkehlchen/history/events.py#L125-L127

This needs to change.

### System Description
Operating system: Any 
Rotki version: 1.26.2

## Task

- [ ] Make it so that the ignore_sync setting is respected when querying a single exchange.
- [ ] Write a test for it
- [ ] See if there is any other places we should respec this setting and we are not doing so.

**Comment by crunchy-roll** [comment]
Hello, I'm interested in contributing to rotki.

Can I try to fix this?

At first glance, I think we can change all instances of `ExchangeManager.connected_exchanges.get(location)` to use `ExchangeManager.iterate_exchanges(location)` wherever the ignore_sync setting is to be respected.

**Comment by yabirgb** [comment]
closed in https://github.com/rotki/rotki/pull/5314
