### ISSUE TITLE
Frontend pending issues for v1.27

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#5414]
## Problem Definition

@rotki/backend Let's add any pending issues here so that @rotki/frontend can pick them and fix them. 

## TODO 

- [x] ~~Updates explorers to support Optimism~~ Done from merged PR
- [x] Add RPC node management for Optimism - @lukicenturi https://github.com/rotki/rotki/pull/5425
- [x] Fix counterparties for the optimism decoders we added - @lukicenturi  https://github.com/rotki/rotki/pull/5384
![2023-01-17_12-41](https://user-images.githubusercontent.com/1658405/212896846-ca951927-e58a-4a1a-818d-6413081857f8.png)
Also hop decoder and generally all decoders under optimism need to have their counterparties added to the frontend

- [x] Move this multichain etherscan servicekey to tabs - @lukicenturi  https://github.com/rotki/rotki/pull/5422
![image](https://user-images.githubusercontent.com/26648140/213086621-eca1589b-19d8-4b5a-9099-b6587dc004e1.png)
- [x] Frontend part for https://github.com/rotki/rotki/pull/5426 @kelsos 
- [x] Nothing happening at restart after Global DB upgrade @lukicenturi 
- [x] Add multple addresses at evm transactions filtering @lukicenturi 
- [x] Optimism etherscan key update exposes implementation detail to confirmation. It should be replaced with a proper resource/text. @lukicenturi 
![image](https://user-images.githubusercontent.com/2269732/213770885-9eb85342-ce81-4202-815b-e120d038a804.png)

@lukicenturi if you pick any of them can you add a note next to the issue?
