### ISSUE TITLE
Consider merging ETH and ETH2 as assets

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#5489]
## Abstract

ETH and ETH2 are the same thing. We, just like the rest of the community, called locked ETH as ETH2 but in reality it's the same asset, just located in the CL/beacon chain.

We already have a setting to treat ETH == ETH2 in graphs/balances etc. so this issue is not urgent, but it may eventually make sense to merge those two assets.

## Task

- [ ] Think about whether this would make sense and especially if accounting woudl work out properly and what changes would the inability to determine between locked/illiquito to normal/liquid ETH bring.
- [ ] If implemented make sure to remove the treat ETH == ETH2 setting
- [ ] Think of other problems that may arise and spec them out.
