### ISSUE TITLE
Average cost basis method - all transactions unrealistic loss

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#5561]
## Problem Definition

This was also reported by @a7e8 in discord.

Running a PnL report for a random address (say `0x72c3d8b1F8B34B075C18498B66CaEabC11045F79`) from etherscan seem to report an unrealistically big loss for each transaction.

#### FiFo

![2023-02-05_01-09_1](https://user-images.githubusercontent.com/1658405/216794954-2359b416-5fc1-43e2-9aee-0f1c48b0f39c.png)

#### Average cost basis

![2023-02-05_01-10](https://user-images.githubusercontent.com/1658405/216794962-ed91da82-d73a-464c-aa94-bfd71be3168f.png)

## Task

- [ ] Figure out what exactly is wrong and fix it.
- [ ] Also test ACB more and add more test cases.
- [x] Also make sure to remind frontend to properly rename it to Average cost basis. (done at https://github.com/rotki/rotki/pull/5564)

### System Description

Operating system: Any
Rotki version: 1.27.0

**Comment by LefterisJP** [comment]
All right so to solve our various misunderstandings I thought I should write down here. I researched the cost basis taxation rules for the 3 jurisdictions that we know use something they call average cost basis. At least UK, France and Canada.

(screenshot below from: https://koinly.io/blog/calculate-cost-basis-crypto-bitcoin/)

![2023-02-08_21-26](https://user-images.githubusercontent.com/1658405/217664210-24d204e0-ebf2-455f-aad5-b3cce0a9b692.png)

Now .. France is very different and koinly is wrong to include them together. Had a very extensive chat with @adrienlacombe-ledger about this. It's not hard ... but very different. It includes the entire portfolio value at any single time across all assets. So it's not per-asset. Which makes it into a category on its own. Will make an issue about it.

Now the good new. Unless I am really tired both Canada and the UK use the same exact formula and it's set and easy to calculate with examples from both the Canada Revenue Agency and the UK's HM's Revenue and customs website.

## Canada

The Canadian Revenue agency has a definition of their average cost basis which they call adjusted cost basis here: https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/about-your-tax-return/tax-return/completing-a-tax-return/personal-income/line-12700-capital-gains/calculating-reporting-your-capital-gains-losses/adjusted-cost-base.html

There is a link to a very extensive pdf there: https://www.canada.ca/content/dam/cra-arc/formspubs/pub/t4037/t4037-22e.pdf
It includes a very extensive explanation of how taxation with ACB works in Canada including the superificial loss rule which is [out of scope](https://github.com/rotki/rotki/issues/4024) for this fix.

At page 23 is a nice example of how ACB is calculated:

![2023-02-08_23-25](https://user-images.githubusercontent.com/1658405/217666327-0789c8e3-8ba3-4db3-947c-907ef665b6c2.png)

But the most extensive example is in: https://www.adjustedcostbase.ca/blog/how-to-calculate-adjusted-cost-base-acb-and-capital-gains/

That includes formulas (which as it turns out are the same as needed for the UK -- as we will see below)

### Step 1

Buy 100 share for 50/share + 10 fees

Total Shares: 100
Total ACB: [Previous Total ACB] + ([Share Price] x [Number of Shares Purchased]) + [Transaction Costs] = 50*100 + 10 = 5010

### Step 2

Sell 50 shares, 120/share + 10 fees

Total Shares: 50

PnL: ([Share Price] x [Number of Shares Sold]) – [Transaction Costs] – (([Total ACB] / [Previous Number of Shares]) x [Number of Shares Sold]) = (120 *50) - 10 - (5010/100)* 50 = 3485.

Total ACB: [Previous Total ACB] x (([Previous Number of Shares] – [Number of Shares Sold]) / [Previous Number of Shares]) = 5010*(100 - 50) / 100 = 2505

### Step 3

Buy 50 shares, 130/share + 10 fees

Total shares: 100

Total ACB: [Previous Total ACB] + ([Share Price] x [Number of Shares Purchased]) + [Transaction Costs] = 2505 + 130*50 + 10 = 9015

### Step 4

Sell 40 shares 90/shae + 10 fees

Total shares: 60

PnL: ([Share Price] x [Number of Shares Sold]) – [Transaction Costs] – (([Total ACB] / [Previous Number of Shares]) x [Number of Shares Sold]) = 40*90 - 10 - (9015/100)*40 = -16

Total ACB: [Previous Total ACB] x (([Previous Number of Shares] – [Number of Shares Sold]) / [Previous Number of Shares]) = 9015*(100 - 40)/100 = 5409

## United Kingdom

The UK's HM Revenue service website has an extensive guide on how taxation in ACB should work here: https://www.gov.uk/government/publications/shares-and-capital-gains-tax-hs284-self-assessment-helpsheet/hs284-shares-and-capital-gains-tax-2019

That includes extra rules like the shared pooling with the same day and bed and breakfasting rules which [are out of scope](https://github.com/rotki/rotki/issues/3941) for this issue.

For the simple ACB case, that document refers to "Example 3" which is a pdf document: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/877369/HS284_Example_3_2020.pdf

![2023-02-08_23-38](https://user-images.githubusercontent.com/1658405/217667284-012814ea-c925-41b5-9d7d-ec6d895941c7.png)
![2023-02-08_23-38_1](https://user-images.githubusercontent.com/1658405/217667303-f24d9a26-97cc-4947-818c-f99b4dc67ed4.png)

It may not seem like it at first but the calculation is the same as Canada. The terminology is a bit different but in the end it looks like the same approach. Let's write it down. Simplifying the British stuff (100p = 1£) and just using the $ symbol instead.

### Step 1
Buy 1000 shares,  $4/share + $150 fees

Shares: 1000
Pool cost: 4150  (this is the "Total ACB" in Canadian terms)

### Step 2
Buy 500 shares $4.10/share + $80 fees

Shares: 1500
Pool cost: 500*4.10+80 + 4150 = 6280

### Step 3
Sell 700 shares $4.8/share + $100 fees

Shares: 800
Allowable cost: 6280 * 700/1500 = 2931
         -> Previous ACB * (sold shares/total shares at time)

PnL: (shares_sold *rate) - fee - allowable_cost
PnL: (700*4.8) - 100 - 2931
PnL: 329

New pool cost: Old - Allowable Cost = 6280-2931 = 3349

## Step 4
Sell 400 shares 5.2/share + 105 fee

Shares: 400
Allowable cost: 3349 * (400/800) = 1674.5

PnL: (shares_sold*rate) - fee - allowale_cost = (400*5.2) - 105 - 1674.5 = 300.5

New pool cost: Old - Allowable Cost = 3349-1674.5 = 1674.5

**Comment by LefterisJP** [comment]
Should be handled by https://github.com/rotki/rotki/pull/5572 and will be present in 1.27.1
