### ISSUE TITLE
Automatically mark an address as exchange deposit (at least for Kraken)

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#5627]
## Abstract

Exchange deposit addresses are unique per users, and users can generate new ones too. So it's literally impossible to automatically tag them as such. But at least for kraken I have noticed that they are contracts and that they all share the same bytecode.

So it may be possible to detect them automatically.

## Notes

This should be worked on only after https://github.com/rotki/rotki/issues/5626 is done.

An example deposit address is here: [0x02bc8b778215159b1d32eee9224da84f1549215d](https://etherscan.io/address/0x02bc8b778215159b1d32eee9224da84f1549215d#code). It's an unverified contract so we don't know what it does exactly. But ... it shares the bytecode with another `302299` as of the time of writing!!! 

## Task

- [ ] Investigate if all deposit addresses to kraken share this bytecode.
- [ ] Investigate if deposit addresses for other exchanges follow similar patterns
- [ ] If confirmed then use this knowledge to check if the address you send to is a contract and check the bytecode and if it matches then mark it with the proper properties (assuming #5626 is implemented). Here we would need to probably use some cache rules to not repeat checks. So if something is already marked with a property not make network queries etc.

**Comment by LefterisJP** [comment]
Not sure if this makes sense. I think what makes more sense is that if you have kraken(or any other exchange) connected and we get the information from there, to just match them.
