### ISSUE TITLE
Reintroduce e2e tests for vue.js app

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#638]
## Problem Definition

The e2e suite was helpful in catching regressions and accidental breakage of the UI. Unfortunately, the e2e tests depend a lot on the implementation and thus the old tests are broken.

- [x] Ensure that the `application_launch.spec.ts` runs successfully
- [x] Ensure that the `create_account.spec.ts` runs successfully
- [ ] Ensure that the `dashboard.spec.ts` runs successfully
- [x] Ensure that the `otc_trades.spec.ts` runs successfully
- [x] Ensure that the `settings_accounting.spec.ts` runs successfully #887
- [x] Ensure that the `account_balances.spec.ts` runs successfully #1062
- [x] Ensure that the `settings_general.spec.ts` runs successfully #821
- [x] Ensure that the `api-keys.spec.ts` runs successfully
- [ ] Add spectron smoketests that run under the [ui tests] flag on CI

After fixing the tests
- [x] Ensure that they are running properly on CI
- [x] Update the UI test CI configuration
- [x] Create a Cron job on CI to run them nightly 
- [ ] Fix tests on OSX

**Comment by kelsos** [comment]
I am re-opening this since we have some cases that are not covered yet. I will continue adding to the tests.

**Comment by kelsos** [comment]
Spectron has been deprecated, -> https://github.com/electron-userland/spectron
Dashboard spec is covered by the other tests
