### ISSUE TITLE
Easier onboarding - default rotki username, only prompt password

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#6456]
## Abstract

One of the things that confuses new users is the concept of a local username. It's really unnecessary for most users. It's simply an identifier. That combined with the fact that most users will only have 1, and all premium users can only have 1 per premium api key makes the username redundant.

What's more many premium users seem to confuse the web2 username/password of the website where they can buy & manage the premium subscription with the username/password of the app.

We want to mitigate all these and offer easier onboarding.

## Task

Address the above by: (can be refined via UX/UI input from @originalrfr)

- [ ] Move the username/password sign in menu into an advanced menu that's hidden. Having to choose an account to sign in is something 95% of the users won't use. A premium subscription is tied to one user, and most users should have only one user, either free or premium.
- [ ] For completely new users auto-generate a default username and a default password, which they will be encouraged to change later. So opening the app will have no friction. Just the questions about keeping analytics and other parts of the wizard.
- [ ] Each time you open the app again, you will simply be prompted to unlock your rotki with a password. User choice should go away by default.

**Comment by kelsos** [comment]
## Notes 
For the advanced mode part of this (for the application at least) we could replace the username input with a drop-down menu with the existing accounts (it should be easily doable).
So that users can select the account/profile from the dropdown. 

Since the dropdown would be limited to existing accounts it should make it more obvious that this is the local account.

We could also potentially update the terminology from `account` to `profile` in order to separate it from the remote account that will still be referenced as account.

**Comment by originalrfr** [comment]
To review: https://www.figma.com/file/msxmKajRPLYiDDmsP60Ndh/Design-System-v1.1?type=design&node-id=869%3A59466&mode=design&t=BEsTKrWJMs7efPBI-1
