### ISSUE TITLE
Some of the imported custom rotki events are of illegal types and not included in PnL

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#6550]
## Problem Definition
Importing custom rotki events can lead to some event types not being legal and not included in the PnL

Example csv:

```csv
Type,Location,Currency,Amount,Fee,Fee Currency,Description,Timestamp
Income,external,HBAR,10,1,HBAR,Binance to Cold Wallet,1658912400000
```

This will lead to the  events being of unknown type as even seen in the UI due to the "?".

![2023-08-25_16-22](https://github.com/rotki/rotki/assets/1658405/caee12f9-fdc2-4d38-9de6-33b79aa98172)

And this will also lead to the PnL not taking them into account due to the unknown type.

## Task

- [ ] make sure the custom import for rotki events have only valid combinations of events
- [ ] Introduce a DB data migration to fix all the wrongly imported event type/subtypes. The DB data migration will only exist for a potential 1.30.2 (or other patch release). In next DB upgrade we should include the migration's content and delete the migration.
- [ ] Test manually and automatically with the example csv

**Comment by yabirgb** [comment]
Should be addressed in https://github.com/rotki/rotki/pull/6553. Anything left or can we close it?
