### ISSUE TITLE
Support GMX v1 in arbitrum.

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#7086]
## Abstract

Support the GMX protocol in arbitrum: https://gmx.io/

## Task

- [x] Support querying GMX positions (#7674)
- [x] Decode GMX events (#7309 and #7394) 
- [ ] Support querying GMX staking balances
