### ISSUE TITLE
Improve ETH staking exit/withdrawal handling

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#7245]
## Abstract

The way ETH staking withdrawals work now, is good for 99% of the cases but could be improved for edge cases.

The way it works is the following. We get them from either [etherscan](https://github.com/rotki/rotki/blob/b106564d79ab9a6407df783857bac262fbdbdbb7/rotkehlchen/chain/ethereum/etherscan.py#L41) or [blockscout](https://github.com/rotki/rotki/blob/b106564d79ab9a6407df783857bac262fbdbdbb7/rotkehlchen/externalapis/blockscout.py#L114) (and soon also beaconcha.in). A withdrawal itself does not contain any data on whether it's an exit or not.

At the moment to determine that we have a [periodic task](https://github.com/rotki/rotki/blob/b106564d79ab9a6407df783857bac262fbdbdbb7/rotkehlchen/tasks/manager.py#L603) that runs from time to time and goes through all withdrawals and marks them as exits [here](https://github.com/rotki/rotki/blob/b106564d79ab9a6407df783857bac262fbdbdbb7/rotkehlchen/chain/ethereum/modules/eth2/eth2.py#L522).

It does that by:

1. Filtering for only active (non-exited) validators.
2. For those validators, query beaconcha.in for validator data and see if an exit has been performed. https://github.com/rotki/rotki/blob/b106564d79ab9a6407df783857bac262fbdbdbb7/rotkehlchen/chain/ethereum/modules/eth2/eth2.py#L548-L557
3. If yes, then get the exit epoch and find the latest withdrawal for that validator and mark it as exit if it's not one as long as it matches the epoch timestamp. https://github.com/rotki/rotki/blob/b106564d79ab9a6407df783857bac262fbdbdbb7/rotkehlchen/db/eth2.py#L176-L195

Then in accounting the logic is the following:
https://github.com/rotki/rotki/blob/b106564d79ab9a6407df783857bac262fbdbdbb7/rotkehlchen/history/events/structures/eth2.py#L206-L235

All withdrawals are pure income and taxable, but if it's an exit, the principal of 32 ETH does not count as profit.

## Motivation

The above **should work** for the majority of users but has multiple points that can be improved.

The edge cases that can happen that I can picture are:

- Someone has done a doule deposit to the validator and has 64 or more ETH locked in there. And so the first withdrawal is already > 32 ETH, but it's not an exit.
- Someone is slashed and is exiting the validator with less than 32 ETH.
- A validator still has 0x0 withdrawals credentials, which means no withdrawal address set. They set the withdrawal address after they have gathered a very big amount of ETH and their first withdrawal is huge but still not really an exit.

The point that we can improve are:
- ~~At point (2) of the abstract above we query beaconchain for each non-exited validator. This is too much. We can optimize here. Set a minimum amount that we consider a withdrawal, and for anything above it check if it was an exit by querying beaconchain.~~ -> No there can be slashing sending you to zero exit.
- For accounting the above logic will not count correctly some edge cases:
    * any exits done by the few people (~15?) who made double deposits by mistake to their validators. In that case the validator's first withdrawal would be >= 32 and it would not be an exit. Yet current logic would see it as exit and not count it as profit.
    *  If a validator gets slashed or exits when due to slashing or inactivity his principal is less than 32 then it's incorrectly counted as profit. While what should happen is that if it's an exit, it should be seen as a loss any thing under 32. So say the exit is 28 ETH, then the validator had a 4 ETH loss.

## Task

Essentially implement what is described in the Motivation section.

- ~~[ ] At the detection of whether something is a withdrawal or an exit improve the logic. Find the non exited validators and then drill that amount down by including any validators with a single withdrawal having amount > `MINIMUM_EXIT_AMOUNT_FOR_ETH_VALIDATOR_WITHDRAWAL`. This constant is gonna be a bit of a quess but should we say 16? This could improve the detection speed a bit by querying beaconchain for less validators. If there is no validators in the set, do not query anything.~~ -> no there is no minimum, though this optimization would work for most cases -- in theory some edge case of slashing to zero would break it
- [ ] At the accounting section we would need to change the logic.
    * [ ] Count profit if it's not an exit.
    * [ ] If it's an exit and it's >= 32 count anything above 32 as profit. If it's a multiple of 32 perhaps yolo it and do modulo 32? At that point we could also compare with deposit. The edge cases of such double deposits are very few.
    * [ ] If it's an exit and it's less than 32 then it's a loss. Count the difference as a loss.

**Comment by LefterisJP** [comment]
This has been done and released with 1.32.0
