### ISSUE TITLE
Support GRT staking in Arbitrum and transferring from mainnet to arbitrum in all cases

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#7358]
## Abstract

This is a continuation of https://github.com/rotki/rotki/issues/2044 which detected GRT staking on mainnet. With this issue we want to also detect staking on arbitrum (since all of GRT staking has now moved there) both for normal accounts and for vesting contracts. Additionally we want to be able to detect the delegation transferring from mainnet to arbitrum

The spec and data given to me for how this is supposed to work are here: https://forum.thegraph.com/t/gip-0046-l2-transfer-tools/4023

We also have a very good example of all these transactions since rotki itself has both a vesting contract and a normal delegating address which I just spent last night transferring to arbitrum.

### Background

The process was a bit complicated and I had to resort to help from the graph's discord to clear some things up. Conversation starts from here: https://discord.com/channels/438038660412342282/789260797620650065/1200582421666603159

In the end I believe we succesfully managed to move them so will put all those example transactions below.

- rotki.eth (https://etherscan.io/address/0x9531c059098e3d194ff87febb587ab07b30b1306) was staking via a vesting contract (which unfortunately #2044 did not detect yet).
- The vesting contract owned by rotki.eth in mainnet was https://etherscan.io/address/0x7d91717579885bfcfec3cb4b4c4fe71c1eedd4de
- The address rotki was doing normal staking/delegation in mainnet with was https://etherscan.io/address/0x8Fe178db26ebA2eEdb22575265bf10A63c395a3d

### Delegation transfer for vesting contract

Transferring the delegation for the vesting contract was a complicated process.

![2024-01-27_00-21](https://github.com/rotki/rotki/assets/1658405/b9e0afc2-aec0-4729-9ca3-a5df78f495a5)

1. Revoke access to previous contracts: https://etherscan.io/tx/0x7de712a2ab4c411ccb064e41a3fd8d77fb44bbc02fa48729330091bda69cacdf
2. Approve contract transfer helpers: https://etherscan.io/tx/0xbb8280cc9ca9de1d33e573a4381d88525a214fc45f84415129face03125ba22f
3. Deposit ETH into the transfer helper contract to pay for gas in L2: https://etherscan.io/tx/0xf254ac1bbfbf07ca21042edd3ff78dad7c3158c8218598b5359b6e415e0977b7
4. This was an unexpected step as you can see from the conversation here: https://discord.com/channels/438038660412342282/789260797620650065/1200595713785081926. We needed a non-zero GRT balance on the vesting contract. So I sent 1 GRT from `0x8Fe178db26ebA2eEdb22575265bf10A63c395a3d` to the vesting contract: https://etherscan.io/tx/0x8a26145e1d6759797fcca61e3f0548400a17de37a0909161477fe1d1b51ca26b
5. At that point the actual step 4 (according to the guides) was possible. Essentially submit the transaction to create the vesting contract on arbitrum L2: https://etherscan.io/tx/0xa4c67ecf1bbf20510a37a27b15a8dd5f22ffffbac06f199cebefd1d7ab0da350
6. Transfer the vested, unvested and delegated amount to arbitrum: https://etherscan.io/tx/0x48321bb00e5c5b67f080991864606dbc493051d20712735a579d7ae31eca3d78

### Delegation transfer for a simple staker

As mentioned `0x8Fe178db26ebA2eEdb22575265bf10A63c395a3d` was also staking/delegating to an indexer. Also moved that to arbitrum but instead of moving it to the same address since `0x8Fe178db26ebA2eEdb22575265bf10A63c395a3d` has no activity in arbitrum moved the delegation directly to rotki.eth (`0x9531c059098e3d194ff87febb587ab07b30b1306`).

This was all in a single transaction: https://etherscan.io/tx/0xed80711e4cb9c428790f0d9b51f79473bf5253d5d03c04d958d411e7fa34a92e

## Task

Do it.

- [ ] Detect GRT staking just like in mainnet for arbitrum wallets
- [ ] Detect GRT staking just like in mainnet for arbitrum vesting contracts
- [x] Properly decode transactions for transferring GRT delegation from mainnet to arbitrum for a normal wallet
- [x] Properly decode transactions for transferring GRT delegation from mainnet to arbitrum for a vestring contract.

**Comment by LefterisJP** [comment]
Closed by #7918
