### ISSUE TITLE
Proper support for stargate

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#7648]
## Task

Add proper support for Stargate protocol.

https://stargate.finance/f
https://stargateprotocol.gitbook.io/stargate

## Specification

- [ ] add support for decoding all pool LPing transactions across supported networks
- [ ] detect LPing and staked balances and included them in the address across all supported networks
- [ ] add support for decoding all staking/farming transactions across supported networks
- [ ] add support for decoding all sending/bridging transactions across supported networks
