### ISSUE TITLE
Query contract information from remote sources

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#8153]
Currently we query registries like the curve api or (velo/aero)drome for addresses that are stored in the database and later loaded to the memory. This approach doesn't scale since we have an increasing database size and probably a good % of the users won't use this information. 

## Task

Add new logic to avoid the need of a registry. We will provide a contract reference and we will query remote sources to download the abi and compare it to an existing contract.

- [ ] Spec the feature
- [ ] Implement the logic to query and compare contracts
- [ ] Move decoders like curve, velodrome, aerodrome

## Notes

- We are not sure of the performance of sqlite comparing ABIs so maybe we will need to store a hash
- Use different sources like sorucify, etherscan, blockscout...
- This issue depends on #8152
