### ISSUE TITLE
Eigenlayer AVS rewards, restake eigenpod ETH and more

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#8492]
## Abstract

Eigenlayer rolled out a big upgrade: https://www.blog.eigenlayer.xyz/introducing-the-eigenpod-upgrade/

This will require changes in our integration of Eigenlayer

## Task

- [ ] Implement decoding for AVS rewards claiming
- [ ] Implement decoding for new way of Eigenpod withdrawing
- [ ] Implement decoding for new way of restakign beaconchain rewards immediately on top of eigenlayer
- [ ] Improve the balance query for native restakers by ignoring the delayed withdrawal router as that has now been deprecated.
