### ISSUE TITLE
Relieve pressure on tax report by maintaining backend tasks querying information beforehand

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#968]
## Abstract

If the user has never done a tax report and has a lot of trades it takes a lot of time to create a tax report. And some time it may actually end up being rate limited by cryptocompare due to the sheer number of queries.

Additionally the data that are generated during a tax report such as profit/loss over time and the trades pulled are very useful and we would also need them in other cases.

## Task

Maintain some backend tasks that run every `X` minutes. They should query:

- [x] Cryptocompare hourly historical price data for all assets the user owns. These should be well spaced away from each other to not get the user rate limited.
- [x] Ethereum transactions of the user's accounts
- [x] Trades the user has made in each exchange
